### ISSUE TITLE
Getting error in connection string

### ISSUE THREAD

**Issue by sethvijay** [sanjyotagureddy/dotnetcore-data-ado-generic#1]
Hi, 
I have tried this, with core application, but getting error dbproviderfactory is null.
since connectionstringsettings doesn't contains the name and provider.
can you clearify it.

**Comment by sanjyotagureddy** [comment]
when you reference this project, add a connection string to your main application of the desired type and don't forget to mention the data provider in your connection string.

**Comment by sethvijay** [comment]
how can I pass the provider name in connection string in appsetting.json file, can you elaborate it....?

**Comment by sanjyotagureddy** [comment]
I have fixed the provider issue, you can check the sample Api for reference
